const tr = {
    hakkimda: {
        bas_bolge: {
            yazi: "Malik",
        },
        ana_bolge: {
            baslik_govdesi: {
                yazi_1: "Hakkımda",
                aciklama_1: "Kendimi kısaca anlattığım bölümdür.",
                yazi_2: "İletişim",
                aciklama_2: "Mail adresimi paylaştığım bölümdür.",
            },
            icerik_govdesi: {
                yazi_1: `
                    Kendi halinde takılan biri.
                `,
                yazi_2: `
                    iletisim@malikyalcintuna.com
                `,
            },
        },
        oyunlar : 'Oyunlar',
        oyunlar_aciklama : 'Kelimat & Sayımat',
        oyun_1 : 'Kelimat Oyna!',
        oyun_2 : 'Sayımat Oyna!'
    },
    bas_icerik: {
        baslik: "Hoşgeldin!",
        aciklama: "Bulunduğun web site '6 Eylül 2022 - 12:00' tarihinde kişisel kullanım için açılmıştır."
    },
    kelimat_oyna: "Kelimat Oyna!",
    sikca_sorulan_sorular: {
        soru_1: `Kelimat oyununun amacı nedir?`,
        cevap_1: `Web sitenin mevcut diline bağlı sistem tarafından 5 harfli bir kelime türetilir. Kullanıcı bu kelimeyi 5 hakkı olacak bir şekilde bulmaya çalışır. Girdiği her denemede yazılan kelimeye bağlı harfler üzerinden ipucu verilir. 3. deneme sonucunda hala cevaba ulaşılmamışsa TDK üzerinden cevap olan kelimenin sözcük karşılığı ekrana yansıtılır. Kullanıcı 5 hakkını doğru bir biçimde değerlendiremezse 10 puan kaybeder; değerlendirirse 10 puan kazanır.`
    },
    geri_sayac: {
        baslik: "YKS 2024 Sayaç",

        vakit_ismi_1: "Gün",
        vakit_ismi_2: "Saat",
        vakit_ismi_3: "Dakika",
        vakit_ismi_4: "Saniye",
    },
    alt_bilgi: {
        yazi: "© Bu websitenin tüm telif hakları Malik YALÇINTUNA'ya aittir.",
    },
};

const us = {
    hakkimda: {
        bas_bolge: {
            yazi: "Malik",
        },
        ana_bolge: {
            baslik_govdesi: {
                yazi_1: "About me",
                aciklama_1: "This is the part where I briefly describe myself.",
                yazi_2: "Contact",
                aciklama_2: "This is the section where I share my e-mail address.",
            },
            icerik_govdesi: {
                yazi_1: `
                    One of her own.
                `,
                yazi_2: `
                    iletisim@malikyalcintuna.com
                `,
            },
        },
        oyunlar : 'Games',
        oyunlar_aciklama : 'Kelimat & Sayımat',
        oyun_1 : 'Play Kelimat!',
        oyun_2 : 'Play Sayımat!'
    },
    bas_icerik: {
        baslik: "Welcome!",
        aciklama: "The site was opened for personal."
    },
    kelimat_oyna: "Play Kelimat!",
    sikca_sorulan_sorular: {
        soru_1: `What is the purpose of the kelimat game?`,
        cevap_1: `A 5-letter word is generated by the system based on the current language of the website. The user tries to find this word with 5 chances. In each attempt, a clue is given through letters connected to the written word. If the answer is still not reached after the 3rd attempt, the word equivalent of the answered word is displayed on the screen via TDK. If the user cannot evaluate his 5 rights correctly, he loses 10 points; if he does, he gains 10 points.`
    },
    geri_sayac: {
        baslik: "YKS 2024 Counter",

        vakit_ismi_1: "Day",
        vakit_ismi_2: "Hour",
        vakit_ismi_3: "Minute",
        vakit_ismi_4: "Second",
    },
    alt_bilgi: {
        yazi: "© All copyrights of this website belong to Malik YALÇINTUNA.",
    },
};

export {
    tr,
    us
}